### ISSUE TITLE
I would like to get the crates-io name, if you don't mind

### ISSUE THREAD

**Issue by Drakulix** [Stebalien/udev-rs#1]
Referring to your README:

> If you would like to take over, please file an issue.

I have forked [different libudev bindings](https://github.com/dcuddeback/libudev-rs), which sadly are unmaintained as well and added [a bunch of features](https://github.com/dcuddeback/libudev-rs/pull/17).

Sadly I did not get any response for that PR, but I am actively using and maintaining these bindings for [smithay](https://github.com/Smithay/smithay). So my goal is to get my fork to crates.io, but all good udev names are taken.

I know that this is a different project then yours and that removing your library from crates.io will significantly hurt visibility, but I wanted to kindly ask anyway, because you don't seem to care about this project anymore.

If you are open to transferring ownership, I would like to ask you to [add me as an owner]
(http://doc.crates.io/crates-io.html#cargo-owner), yank your release and then remove yourself as an owner.

Thank you for your time.

**Comment by Stebalien** [comment]
All yours. Ping me when you accept the invite, I can't remove myself until you do.

Fair warning, libudev doesn't properly handle null bytes in attribute values (they *are* technically legal but libudev assumes that attribute values are valid C strings). It also has a bunch of other pitfalls that you'll have to discover for yourself :).

**Comment by Drakulix** [comment]
> All yours. Ping me when you accept the invite, I can't remove myself until you do.

Done. Thanks! :)

> Fair warning, libudev doesn't properly handle null bytes in attribute values (they are technically legal but libudev assumes that attribute values are valid C strings). It also has a bunch of other pitfalls that you'll have to discover for yourself :).

Sounds great...

**Comment by Stebalien** [comment]
All done.
